"""empty message

Revision ID: 46c3742c4e67
Revises: 80ad72996bb0
Create Date: 2022-05-16 21:48:50.658475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c3742c4e67'
down_revision = '80ad72996bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'todo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('todo_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
