"""empty message

Revision ID: 790aaae2e0ca
Revises: d6ea974ca541
Create Date: 2022-05-02 17:47:00.737761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790aaae2e0ca'
down_revision = 'd6ea974ca541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_todo_timestamp'), 'todo', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_timestamp'), table_name='todo')
    op.drop_column('todo', 'timestamp')
    # ### end Alembic commands ###
