"""empty message

Revision ID: 80ad72996bb0
Revises: 64e18249393c
Create Date: 2022-05-16 21:47:22.654566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ad72996bb0'
down_revision = '64e18249393c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('todo_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'todo', ['todo_id'], ['id'])
    op.drop_column('todo', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    op.drop_column('todo', 'todo_id')
    # ### end Alembic commands ###
