"""empty message

Revision ID: cda1d4077c14
Revises: 5289a69c6ad6
Create Date: 2022-05-16 18:59:19.233575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda1d4077c14'
down_revision = '5289a69c6ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todo', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    # ### end Alembic commands ###
